### ISSUE TITLE
2.0 Support?

### ISSUE THREAD

**Issue by ultrabear** [bryanforbes/discord.py-stubs#150]
This is less of an issue and more of a question, but will this library be updated with the release of discord.py 2.0 with mypy compatible type stubs? I understand that discord.py 2.0 alphas come with their own type stubs now, but these are pyright formatted type stubs that do not work under mypy for whatever reason, and they do not seem to have plans to support mypy.
Just wondered about the status of this project, because it would be nice to continue to be able to use mypy with discord.py and not be forced to retire it for a different typechecker that may not catch the same errors (ideally both typecheckers can be used for exhaustiveness)

**Comment by bryanforbes** [comment]
I have no plans to duplicate the efforts of the discord.py team with regards to 2.0. In fact, I've been working with them in order to ensure their typings are correct. The features that are needed for mypy to work with discord.py are being worked on. As soon as those are done, expect mypy to begin to work with discord.py.

**Comment by ultrabear** [comment]
Good to hear mypy will work eventually, ill close this issue now
And thanks for maintaining this library till its EOL, it has been very useful!
